module.exports = [
  {
    id: "1",
    name: "John Doe",
    phoneNumber: "1234567890",
    courseName: "Physics",
    address: "pondy",
  },
  {
    id: "2",
    name: "Jane Smith",
    phoneNumber: "9876543210",
    courseName: "Mathematics",
    address: "cuddalore",
  },
  {
    id: "3",
    name: "John Doe",
    phoneNumber: "5678901234",
    courseName: "Physics",
    address: "villupuram",
  },
  {
    id: "4",
    name: "Emily Davis",
    phoneNumber: "4321098765",
    courseName: "English Literature",
    address: "chennai",
  },
  {
    id: "5",
    name: "Michael Wilson",
    phoneNumber: "8901234567",
    courseName: "History",
    address: "salem",
  },
  {
    id: "6",
    name: "Sarah Taylor",
    phoneNumber: "3456789012",
    courseName: "Chemistry",
    address: "madurai",
  },
  {
    id: "7",
    name: "Robert Anderson",
    phoneNumber: "7654321098",
    courseName: "Biology",
    address: "trichy",
  },
  {
    id: "8",
    name: "Jennifer Brown",
    phoneNumber: "2109876543",
    courseName: "Geography",
    address: "theni",
  },
  {
    id: "9",
    name: "Daniel Thomas",
    phoneNumber: "6789012345",
    courseName: "Economics",
    address: "ooty",
  },
  {
    id: "10",
    name: "Jessica Martinez",
    phoneNumber: "5432109876",
    courseName: "Psychology",
    address: "kodaikanal",
  },
  {
    id: "11",
    name: "Christopher Harris",
    phoneNumber: "9012345678",
    courseName: "Sociology",
    address: "kanchipuram",
  },
  {
    id: "12",
    name: "Maria Jackson",
    phoneNumber: "4567890123",
    courseName: "Political Science",
    address: "thiruvallur",
  },
  {
    id: "13",
    name: "William Lee",
    phoneNumber: "8765432109",
    courseName: "Philosophy",
    address: "erode",
  },
  {
    id: "14",
    name: "Amanda Walker",
    phoneNumber: "3210987654",
    courseName: "Art History",
    address: "tindivanam",
  },
  {
    id: "15",
    name: "Matthew White",
    phoneNumber: "7890123456",
    courseName: "Music",
    address: "marakannum",
  },
  {
    id: "16",
    name: "Olivia Thompson",
    phoneNumber: "6543210987",
    courseName: "Theater",
    address: "pondy",
  },
  {
    id: "17",
    name: "Andrew Garcia",
    phoneNumber: "0123456789",
    courseName: "Film Studies",
    address: "pondy",
  },
  {
    id: "18",
    name: "Lauren Clark",
    phoneNumber: "8765432109",
    courseName: "Anthropology",
    address: "pondy",
  },
  {
    id: "19",
    name: "James Rodriguez",
    phoneNumber: "5432109876",
    courseName: "Anthropology",
    address: "pondy",
  },
  {
    id: "20",
    name: "Megan Hill",
    phoneNumber: "9012345678",
    courseName: "Anthropology",
    address: "pondy",
  },
];
